spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://weather_postgres_db:5432/weather_db
    password: docker
    username: docker
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    user: docker
    password: docker
    url: jdbc:postgresql://weather_postgres_db:5432/weather_db
  #    url: jdbc:postgresql://localhost:5460/hungman
#  jdbc:postgresql://weather_postgres_db:5432/weather_db

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF

  thymeleaf:
    cache: 'false'
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: web-project-weather
server:
  port: '9097'
